-- DATABASE: acch --
CREATE DATABASE acch
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'pt_BR.utf8'
    LC_CTYPE = 'pt_BR.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- Table: public.conta_bancaria --

CREATE TABLE public.conta_bancaria
(
    idconta integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tipoconta character(2) COLLATE pg_catalog."default",
    agencia integer,
    numeroconta integer NOT NULL,
    saldo double precision,
    banco character varying COLLATE pg_catalog."default",
    limitecredito double precision,
    CONSTRAINT conta_bancaria_pkey PRIMARY KEY (numeroconta)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.conta_bancaria
    OWNER to postgres;

-- Table: public.movimento --

CREATE TABLE public.movimento
(
    idmovimento integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tipomovimento character varying(1) COLLATE pg_catalog."default",
    numeroconta integer,
    valormovimento double precision,
    dtmovimento date DEFAULT CURRENT_DATE,
    CONSTRAINT movimento_pkey PRIMARY KEY (idmovimento),
    CONSTRAINT conta_corrente_fkey FOREIGN KEY (numeroconta)
        REFERENCES public.conta_bancaria (numeroconta) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.movimento
    OWNER to postgres;
CREATE INDEX fki_conta_corrente_fkey
    ON public.movimento USING btree
    (numeroconta)
    TABLESPACE pg_default;